---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container
  namespace: default
  labels:
    app.kubernetes.io/name: multi-container
    app.kubernetes.io/instance: kubetail-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-container
      app.kubernetes.io/instance: kubetail-dev
  replicas: 3
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multi-container
        app.kubernetes.io/instance: kubetail-dev
    spec:
      containers:
        - name: loggen
          image: docker.io/kubetail/loggen:0.1.2
          resources: {}
        - name: loggen-ansi
          image: docker.io/kubetail/loggen:0.1.2
          args: ["-ansi"]
          resources: {}
