title: "[Product Spec] "
labels: ["Product Spec"]
body:
  - type: markdown
    attributes:
      value: |
        ## Problem Statement/Background

        <-- What problem are we solving? For who? Why is it important? What evidence do we have?  -->

        ## Proposals & Alternatives

        <-- How can we solve the problem? What are the pros and cons of each approach? -->

        ## Plan (Launch Plan, Success Metrics)

        <-- What will we build? How will we measure success? How long will it take to build? -->
