---
kind: ServiceAccount
apiVersion: v1
automountServiceAccountToken: true
metadata:
  name: kubetail
  namespace: kubetail
  annotations:
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubetail
  namespace: kubetail
  annotations:
data:
  config.yaml: |
    addr: :4000
    auth-mode: cluster
    session:
      secret: REPLACEME
    csrf:
      secret: REPLACEME
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail
  annotations:
rules:
- apiGroups: ["", apps, batch]
  resources: [cronjobs, daemonsets, deployments, jobs, namespaces, nodes, pods, pods/log, replicasets, statefulsets]
  verbs: [get, list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetail
subjects:
- kind: ServiceAccount
  name: kubetail
  namespace: kubetail
---
kind: Service
apiVersion: v1
metadata:
  name: kubetail
  namespace: kubetail
  annotations:
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/instance: kubetail
  ports:
  - name: kubetail
    protocol: TCP
    appProtocol: http
    port: 80
    targetPort: kubetail
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubetail
  namespace: kubetail
  annotations:
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: kubetail
      app.kubernetes.io/instance: kubetail
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubetail
        app.kubernetes.io/instance: kubetail
      annotations:
        checksum/config: 19797507f315b0053e34ee4e371d68fa04404eb38ae3526f4091bd70a36f7e5d
    spec:
      automountServiceAccountToken: true
      serviceAccountName: kubetail
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: kubetail
        #image: docker.io/kubetail/kubetail:0.4.5
        image: kubetail:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        imagePullPolicy: IfNotPresent
        env:
        envFrom:
        ports:
        - name: kubetail
          protocol: TCP
          containerPort: 4000
        args:
        - --config=/etc/kubetail/config.yaml
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: kubetail
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: kubetail
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 30
        resources:
        volumeMounts:
        - name: config
          mountPath: /etc/kubetail
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: kubetail
      nodeSelector:
      affinity:
      tolerations:
