// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type HealthCheckResponse struct {
	Status    HealthCheckStatus `json:"status"`
	Message   *string           `json:"message,omitempty"`
	Timestamp time.Time         `json:"timestamp"`
}

type LogRecord struct {
	Timestamp time.Time `json:"timestamp"`
	Message   string    `json:"message"`
}

type Query struct {
}

type Subscription struct {
}

type HealthCheckStatus string

const (
	HealthCheckStatusSuccess HealthCheckStatus = "SUCCESS"
	HealthCheckStatusFailure HealthCheckStatus = "FAILURE"
)

var AllHealthCheckStatus = []HealthCheckStatus{
	HealthCheckStatusSuccess,
	HealthCheckStatusFailure,
}

func (e HealthCheckStatus) IsValid() bool {
	switch e {
	case HealthCheckStatusSuccess, HealthCheckStatusFailure:
		return true
	}
	return false
}

func (e HealthCheckStatus) String() string {
	return string(e)
}

func (e *HealthCheckStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HealthCheckStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HealthCheckStatus", str)
	}
	return nil
}

func (e HealthCheckStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
