---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaoskube
  namespace: default
  labels:
    app.kubernetes.io/name: chaoskube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaoskube
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaoskube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaoskube
subjects:
- kind: ServiceAccount
  name: chaoskube
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaoskube
  namespace: default
  labels:
    app.kubernetes.io/name: chaoskube
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaoskube
  namespace: default
  labels:
    app.kubernetes.io/name: chaoskube
subjects:
- kind: ServiceAccount
  name: chaoskube
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaoskube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: chaoskube
  labels:
    app.kubernetes.io/name: chaoskube
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: chaoskube
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chaoskube
    spec:
      serviceAccountName: chaoskube
      containers:
      - name: chaoskube
        image: ghcr.io/linki/chaoskube:v0.31.0
        args:
        - --interval=2m
        - --labels=app.kubernetes.io/name=loggen
        - --namespaces=default
        - --minimum-age=4m
        - --no-dry-run
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
---
