---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: default
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: init
              image: busybox:1.28
              command:
                - /bin/sh
                - -c
                - date; echo Initializing pod
          containers:
            - name: hello
              image: busybox:1.28
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
