apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-example
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: daemonset-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: daemonset-example
    spec:
      containers:
      - name: daemonset-example
        image: alpine:3.22.0
        # will print the name of the host machine the pod is running on
        command: ["sh", "-c"]
        args:
          - |
            echo "This pod is running on $(cat /etc/hostname)"
            while true; do sleep 3600; done
        volumeMounts:
        - name: hostname
          mountPath: /etc/hostname
          readOnly: true
      volumes:
      - name: hostname
        hostPath:
          path: /etc/hostname
          type: File

