apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: os-release-daemonset
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: os-release
  template:
    metadata:
      labels:
        app.kubernetes.io/name: os-release
    spec:
      containers:
      - name: log-os-release
        image: busybox
        # will print the os-release of the host machine
        command: ["sh", "-c"]
        args:
          - |
            cat /etc/os-release
            while true; do sleep 3600; done
        volumeMounts:
        - name: os-release
          mountPath: /etc/os-release
          readOnly: true
      volumes:
      - name: os-release
        hostPath:
          path: /etc/os-release
          type: File


