FROM rust:1.88-slim AS builder

WORKDIR /work

RUN apt-get update && apt-get install -yq protobuf-compiler

# Install Rust dependencies (for cache)
COPY crates/ ./crates
COPY proto/ ./proto
RUN cd crates && cargo fetch

# Build
RUN cd crates && cargo build --release

# -----------------------------------------------------------

FROM debian:stable-slim AS final

WORKDIR /cluster-agent

# copy grpc-health-probe
COPY --from=ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.38 /ko-app/grpc-health-probe /bin/grpc_health_probe

# copy executable
COPY --from=builder /work/crates/target/release/cluster_agent cluster-agent

ENTRYPOINT ["./cluster-agent"]
CMD []
