FROM rust:1.84.1 AS rustbuilder

WORKDIR /work

RUN rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl
RUN apt-get update && apt-get install -yq musl-tools protobuf-compiler

# Install Rust dependencies (for cache)
COPY crates/rgkl/Cargo.toml ./crates/rgkl/Cargo.toml
COPY crates/rgkl/Cargo.lock ./crates/rgkl/Cargo.lock
COPY crates/rgkl/src/main.rs ./crates/rgkl/src/main.rs
RUN cd crates/rgkl && cargo fetch

# Copy code
COPY . .

# Detect architecture and build statically
RUN ARCH="$(uname -m)" && \
    if [ "$ARCH" = "x86_64" ]; then \
      TARGET="x86_64-unknown-linux-musl"; \
    elif [ "$ARCH" = "aarch64" ]; then \
      TARGET="aarch64-unknown-linux-musl"; \
    else \
      echo "Unsupported architecture: $ARCH"; exit 1; \
    fi && \
    cd crates/rgkl && \
    cargo build --target=$TARGET && \
    mkdir -p /out && \
    cp target/$TARGET/debug/rgkl /out/rgkl

# -----------------------------------------------------------

FROM alpine:3.20.0

WORKDIR /cluster-agent

COPY --from=rustbuilder /out/rgkl /usr/local/bin/rgkl
COPY .tilt/cluster-agent .

ENTRYPOINT ["./cluster-agent"]