FROM rust:1.84.1 AS rustbuilder

WORKDIR /work

# System dependencies
RUN apt-get update && apt-get install -yq patchelf protobuf-compiler

# Install Rust dependencies (for cache)
COPY crates/rgkl/Cargo.toml ./crates/rgkl/Cargo.toml
COPY crates/rgkl/Cargo.lock ./crates/rgkl/Cargo.lock
COPY crates/rgkl/src/main.rs ./crates/rgkl/src/main.rs
RUN cd crates/rgkl && cargo fetch

# Copy code
COPY . .

# Build
RUN cd crates/rgkl && cargo build --release

# Make bundle
RUN \
    ARCH="$(uname -m)" && \
    if [ "$ARCH" = "x86_64" ]; then \
      LIBC_PATH="/lib/x86_64-linux-gnu"; \
      LINKER_PATH="/lib64/ld-linux-x86-64.so.2"; \
    elif [ "$ARCH" = "aarch64" ]; then \
      LIBC_PATH="/lib/aarch64-linux-gnu"; \
      LINKER_PATH="/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1"; \
    else \
      echo "Unsupported architecture: $ARCH"; exit 1; \
    fi && \
    mkdir -p /out/lib && \
    cp -v /work/crates/rgkl/target/release/rgkl /out/rgkl && \
    cp -v $LIBC_PATH/libc.so.6 /out/lib/ && \
    cp -v $LIBC_PATH/libgcc_s.so.1 /out/lib/ && \
    cp -v $LINKER_PATH /out/lib/ld-linux.so

RUN patchelf --set-rpath "\$ORIGIN/lib" /out/rgkl

# -----------------------------------------------------------

FROM alpine:3.20.0

WORKDIR /cluster-agent

RUN apk add libc6-compat

COPY --from=rustbuilder /out /rgkl
COPY .tilt/cluster-agent .

ENTRYPOINT ["./cluster-agent"]
CMD []
