kind: Deployment
apiVersion: apps/v1
metadata:
  name: echoserver
  namespace: default
  labels:
    app.kubernetes.io/name: echoserver
    app.kubernetes.io/instance: kubetail-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: echoserver
      app.kubernetes.io/instance: kubetail-dev
  replicas: 3
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echoserver
        app.kubernetes.io/instance: kubetail-dev
    spec:
      containers:
      - name: echoserver
        image: kubetail/echoserver:0.1.1
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        resources: {}
