---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: kubetail-agent
  namespace: default
  labels:
    app.kubernetes.io/name: kubetail-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubetail-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubetail-agent
    spec:
      containers:
      - name: kubetail-agent
        image: kubetail-agent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        resources: {}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
