kind: ConfigMap
apiVersion: v1
metadata:
  name: kubetail
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
data:
  config.yaml: |
    allowed-namespaces: []
    dashboard:
      addr: :8080
      auth-mode: token
      base-path: /
      cluster-api-endpoint: http://kubetail-cluster-api.kubetail-system.svc:8080
      environment: cluster
      gin-mode: debug
      ui:
        cluster-api-enabled: true
      session:
        secret: REPLACEME
        cookie:
          name: kubetail_dashboard_session
          path: /
          max-age: 2592000
          secure: false
          http-only: true
          same-site: lax
      csrf:
        enabled: true
        secret: REPLACEME
        field-name: csrf_token
        cookie:
          name: kubetail_dashboard_csrf
          path: /
          max-age: 43200
          secure: false
          http-only: true
          same-site: strict
      logging:
        enabled: true
        level: debug
        format: pretty
        access-log:
          enabled: true
          hide-health-checks: true
      tls:
        enabled: false
        cert-file:
        key-file:
    cluster-api:
      addr: :8080
      base-path: /
      gin-mode: debug
      agent-dispatch-url: kubernetes://kubetail-cluster-agent:50051
      csrf:
        enabled: true
        secret: REPLACEME
        field-name: csrf_token
        cookie:
          name: kubetail_cluster_api_csrf
          path: /
          max-age: 43200
          secure: false
          http-only: true
          same-site: strict
      logging:
        enabled: true
        level: debug
        format: pretty
        access-log:
          enabled: true
          hide-health-checks: true
      tls:
        enabled: false
        cert-file:
        key-file:
    cluster-agent:
      addr: :50051
      logging:
        enabled: true
        level: debug
        format: pretty
      tls:
        enabled: false
        cert-file:
        key-file:
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubetail-dashboard
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: dashboard
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-dashboard
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: dashboard
rules:
- apiGroups: [""]
  resources: [namespaces, nodes]
  verbs: [get, list, watch]
- apiGroups: ["", apps, batch]
  resources: [cronjobs, daemonsets, deployments, jobs, pods, pods/log, replicasets, statefulsets]
  verbs: [get, list, watch]
- apiGroups: [authentication.k8s.io]
  resources: [tokenreviews]
  verbs: [create]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-dashboard
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetail-dashboard
subjects:
- kind: ServiceAccount
  name: kubetail-dashboard
  namespace: kubetail-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-dashboard
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: dashboard
rules:
- apiGroups: [discovery.k8s.io]
  resources: [endpointslices]
  verbs: [list, watch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-dashboard
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: dashboard
roleRef:
  kind: Role
  name: kubetail-dashboard
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubetail-dashboard
  namespace: kubetail-system    
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubetail-dashboard
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: dashboard
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: kubetail
      app.kubernetes.io/component: dashboard
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubetail
        app.kubernetes.io/component: dashboard
    spec:
      serviceAccountName: kubetail-dashboard
      containers:
      - name: kubetail-dashboard
        image: kubetail-dashboard
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        args:
        - --config=/etc/kubetail/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/kubetail
          readOnly: true
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        resources: {}
      volumes:
      - name: config
        configMap:
          name: kubetail
---
kind: Service
apiVersion: v1
metadata:
  name: kubetail-dashboard
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: dashboard
spec:
  selector:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: dashboard
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
    appProtocol: http
---    
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubetail-cluster-api
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-api
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-cluster-api
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-api
rules:
- apiGroups: [discovery.k8s.io]
  resources: [endpointslices]
  verbs: [list, watch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-cluster-api
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-api
roleRef:
  kind: Role
  name: kubetail-cluster-api
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubetail-cluster-api
  namespace: kubetail-system    
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubetail-cluster-api
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-api
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: kubetail
      app.kubernetes.io/component: cluster-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubetail
        app.kubernetes.io/component: cluster-api
    spec:
      serviceAccountName: kubetail-cluster-api
      containers:
      - name: kubetail-cluster-api
        image: kubetail-cluster-api
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        args:
        - --config=/etc/kubetail/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/kubetail
          readOnly: true
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        resources: {}
      volumes:
      - name: config
        configMap:
          name: kubetail
---
kind: Service
apiVersion: v1
metadata:
  name: kubetail-cluster-api
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-api
spec:
  selector:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-api
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
    appProtocol: http
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubetail-cluster-agent
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-agent
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: kubetail-cluster-agent
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubetail
      app.kubernetes.io/component: cluster-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubetail
        app.kubernetes.io/component: cluster-agent
    spec:
      serviceAccountName: kubetail-cluster-agent
      containers:
      - name: kubetail-cluster-agent
        image: kubetail-cluster-agent
        ports:
        - name: grpc
          protocol: TCP
          containerPort: 50051
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - --config=/etc/kubetail/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/kubetail
          readOnly: true
        - name: varlog
          mountPath: /var/log
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        resources: {}
      volumes:
      - name: config
        configMap:
          name: kubetail
      - name: varlog
        hostPath:
          path: /var/log
---
kind: Service
apiVersion: v1
metadata:
  name: kubetail-cluster-agent
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-agent
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-agent
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kubetail-cluster-agent
  namespace: kubetail-system
  labels: 
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cluster-agent
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kubetail
      app.kubernetes.io/component: cluster-agent
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: kubetail
          app.kubernetes.io/component: cluster-api
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubetail-cli
  namespace: kubetail-system
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cli
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-cli
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cli
rules:
- apiGroups: [""]
  resources: [pods/log]
  verbs: [list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-cli
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/component: cli
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetail-cli
subjects:
- kind: ServiceAccount
  name: kubetail-cli
  namespace: kubetail-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubetail-testuser
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-testuser
rules:
- apiGroups: ["", apps, batch]
  resources: [cronjobs, daemonsets, deployments, jobs, namespaces, nodes, pods, pods/log, replicasets, statefulsets]
  verbs: [get, list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-testuser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetail-testuser
subjects:
- kind: ServiceAccount
  name: kubetail-testuser
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-testuser
  namespace: kubetail-system
rules:
- apiGroups: [discovery.k8s.io]
  resources: [endpointslices]
  verbs: [list, watch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail-testuser
  namespace: kubetail-system
roleRef:
  kind: Role
  name: kubetail-testuser
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubetail-testuser
  namespace: default
