---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggen
  namespace: default
  labels:
    app.kubernetes.io/name: loggen
    app.kubernetes.io/instance: kubetail-dev-1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loggen
      app.kubernetes.io/instance: kubetail-dev-1
  replicas: 3
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loggen
        app.kubernetes.io/instance: kubetail-dev-1
        app.kubernetes.io/version: "0.1.3"
    spec:
      containers:
      - name: loggen
        image: docker.io/kubetail/loggen:0.1.2
        resources: {}
