---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-box
  namespace: default
  labels:
    app.kubernetes.io/name: nats-box
    app.kubernetes.io/instance: kubetail-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats-box
      app.kubernetes.io/instance: kubetail-dev
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats-box
        app.kubernetes.io/instance: kubetail-dev
    spec:
      containers:
      - name: nats-box
        image: natsio/nats-box:0.14.3
        env:
          - name: NATS_URL
            value: nats://nats:4222
        command: ["sleep", "infinity"]
        resources: {}
