PackageIdentifier: Kubetail.Kubetail
PackageVersion: <placeholder>
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: kubetail.exe
    PortableCommandAlias: kubetail
Installers:
  - Architecture: x64
    InstallerUrl: <placeholder>
    InstallerSha256: <placeholder>
  - Architecture: arm64
    InstallerUrl: <placeholder>
    InstallerSha256: <placeholder>
ManifestType: installer
ManifestVersion: 1.10.0
