PackageIdentifier: Kubetail.Kubetail
PackageVersion: <placeholder>
PackageLocale: en-US
Publisher: Kubetail
PublisherUrl: https://www.kubetail.com
PublisherSupportUrl: https://github.com/kubetail-org/kubetail/issues
PackageName: Kubetail CLI
PackageUrl: https://github.com/kubetail-org/kubetail
License: Apache-2.0
LicenseUrl: https://github.com/kubetail-org/kubetail/blob/HEAD/LICENSE
Copyright: Andres Morey
ShortDescription: A real-time logging dashboard for Kubernetes
Moniker: kubetail
Tags:
  - cluster
  - docker
  - k8s
  - kubernetes
  - logging
  - monitoring
ManifestType: defaultLocale
ManifestVersion: 1.10.0
