name: riscv64-post-merge-checks

permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  go-test-riscv64:
    strategy:
      matrix:
        module:
          - cli
          - cluster-api
          - dashboard
          - shared
    runs-on: ubuntu-24.04-riscv
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-environment
        with:
          setup-go: "true"
      - name: Run tests
        working-directory: ./modules/${{ matrix.module }}
        run: go test ./...

  build-cli:
    runs-on: ubuntu-24.04-riscv
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-environment
        with:
          setup-go: "true"
      - name: Build
        working-directory: ./modules/cli
        run: |
          CGO_ENABLED=0 go build -ldflags="-s -w" ./cmd/main.go
