name: publish-krew

permissions:
  contents: read

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  update-krew-index-repo:
    name: Update krew-index repo
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.47
        with:
          krew_template_file: .github/ci-config/krew.yaml
