name: publish-chocolatey

permissions:
  contents: read

on:
  release:
    types:
      - published

jobs:
  trigger-choco-packages-publish-workflow:
    name: Trigger choco-packages publish workflow
    runs-on: ubuntu-24.04
    steps:
      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/cli/v}" >> $GITHUB_OUTPUT
      - name: Trigger workflow
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          repo: kubetail-org/choco-packages
          workflow: publish
          token: ${{ secrets.PUBLISH_CHOCOLATEY_TOKEN }}
          inputs: '{ "version": "${{ steps.version.outputs.version }}", "merge_on_push": true }'
