name: publish

on:
  push:
    tags:
      - '**'

jobs:
  #build:
  #  runs-on: ${{ matrix.runner }}
  #  strategy:
  #    matrix:
  #      runner: [ubuntu-latest, ubuntu-arm64]
  #  steps:
  #    - name: Get tag name
  #      uses: olegtarasov/get-tag@2.1.3
  #      id: tagName
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #    - name: Set up QEMU
  #      uses: docker/setup-qemu-action@v3
  #    - name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v3        
  #    - name: Login to Docker Hub
  #      uses: docker/login-action@v3
  #      with:
  #        username: ${{ secrets.DOCKERHUB_USERNAME }}
  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
  #    - name: Build and push
  #      uses: docker/build-push-action@v5
  #      with:
  #        context: .
  #        platforms: linux/amd64,linux/arm64
  #        push: true
  #        tags: kubetail/kubetail:${{ steps.tagName.outputs.tag }}

  build-and-publish-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@2.1.3
        id: tagName
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kubetail/kubetail:${{ steps.tagName.outputs.tag }}-amd64

  build-and-publish-arm64:
    runs-on: ubuntu-arm64
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@2.1.3
        id: tagName
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up docker
        uses: docker-practice/actions-setup-docker@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kubetail/kubetail:${{ steps.tagName.outputs.tag }}-arm64
        
  #create-manifest:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Get tag name
  #      uses: olegtarasov/get-tag@2.1.3
  #      id: tagName
  #    - name: Login to Docker Hub
  #      uses: docker/login-action@v3
  #      with:
  #        username: ${{ secrets.DOCKERHUB_USERNAME }}
  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
  #    - name: Create and push manifest
  #      run: |
  #        docker manifest create 
  #      uses: docker/build-push-action@v5
  #      with:
  #        context: .
  #        platforms: linux/amd64,linux/arm64
  #        push: true
  #        tags: kubetail/kubetail:${{ steps.tagName.outputs.tag }}
  